### ISSUE TITLE
Unknown command handler

### ISSUE THREAD

**Issue by nathan-fiscaletti** [ctaylo21/termy-the-terminal#44]
Is there a way to add a handler for when the user enters a command that is not known? I want to implement a SQL terminal but I don't want to have to implement a custom command handler for every SQL keyword. I'd rather just accept any generic input and forward it to a SQL client, and then have the output displayed in the terminal.

**Comment by ctaylo21** [comment]
Hi there - it's possible to add the functionality. You could either extend the `customCommands` functionality to have a method for unknown commands or add a separate handler that allows users to override the method called when an unknown command is parsed.

I haven't touched this project in a long time, so I suggest forking it and trying out that functionality yourself. Good luck!
