### ISSUE TITLE
Server Side Processing - Question

### ISSUE THREAD

**Issue by nicpenning** [ctaylo21/termy-the-terminal#45]
What is your recommendation for doing server side processing of custom commands and directories? The idea is that I can use a command and check a database to see if it exists before executing it. I am trying to avoid having commands in the backend and the frontend. 

Thoughts?

**Comment by ctaylo21** [comment]
Sorry about the delay here - I haven't touched this project in a while. I think it should be pretty straightforward to add a server-side component. All of the commands already use Promises. You can just make a command like the existing ones but replace client logic with an API/DB call and resolve with the result.
